title: Joshua Azemoh
brand: Azemoh
email: joshazemoh@gmail.com
tagline: Thinker 路 Learner 路 Builder
motor: Think 路 Learn 路 Create
markdown: kramdown
timezone: Africa/Lagos

disqus_name: azemoh

baseurl: ""

gems: [
  jekyll-paginate
]

exclude: [
  .git,
  .gitignore,
  CNAME,
  assets/icomoon,
  .sass-cache,
  package.json,
  gulpfile.js,
  node_modules,
  README.md,
  '**/*.scss',
  '**/*.ai',
  '**/*.psd',
	'**/*.log'
]

env: "dev"

paginate: 5
paginate_path: "/writing/page:num/"


# SEO
author: Joshua Azemoh
description: "Joshua Azemoh's personal website and technical blog"


# Site Variables

## Menu
home_menu:
- {name: "Home", url: "/#home" }
- {name: "About Me", url: "/#about" }
- {name: "Writing", url: "/writing"}
#- {name: "Demo", url: "#work" }
- {name: "Get In Touch", url: "/#contact" }

## Social links
socialLinks:
- {name: "github", title: "Github", url: "https://github.com/azemoh"}
- {name: "twitter", title: "Twitter", url: "http://twitter.com/josh_azemoh"}
- {name: "linkedin", title: "Linkedin", url: "https://linkedin.com/in/azemoh"}
- {name: "email", title: "joshazemoh@gmail.com", url: "mailto://joshazemoh@gmail.com"}
# - {name: "google-plus", title: "Google+", url: "https://plus.google.com/+JoshuaAzemoh"}
#- {name: "facebook", title: "Facebook", url: "https://facebook.com/azemoh"}
